src/Entity/Apartamento.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Apartamento
 *
 * @ORM\Table(name="apartamento", uniqueConstraints={@ORM\UniqueConstraint(name="url", columns={"url"})})
 * @ORM\Entity(repositoryClass="App\Repository\ApartamentoRepository")
 */
class Apartamento
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=false)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="text", length=65535, nullable=false)
     */
    private $image;

    /**
     * @var int
     *
     * @ORM\Column(name="price", type="integer", nullable=false)
     */
    private $price;

    /**
     * @var string|null
     *
     * @ORM\Column(name="description", type="text", length=65535, nullable=true)
     */
    private $description;

    /**
     * @var string|null
     *
     * @ORM\Column(name="long_description", type="text", length=65535, nullable=true)
     */
    private $longDescription;

    /**
     * @var string|null
     *
     * @ORM\Column(name="latitud", type="string", length=255, nullable=true)
     */
    private $latitud;

    /**
     * @var string|null
     *
     * @ORM\Column(name="longitud", type="string", length=255, nullable=true)
     */
    private $longitud;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean", nullable=false)
     */
    private $active;

    /**
     * @var bool
     *
     * @ORM\Column(name="possible", type="boolean", nullable=false)
     */
    private $possible;

    /**
     * @var string
     *
     * @ORM\Column(name="notes", type="text", length=65535, nullable=false)
     */
    private $notes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $createdAt = 'CURRENT_TIMESTAMP';

    /**
     * @var string|null
     *
     * @ORM\Column(name="hash", type="string", length=255, nullable=true)
     */
    private $hash;

    public function setId(?int $id) : self
    {
        $this->id = $id;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setUrl(?string $url) : self
    {
        $this->url = $url;
        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImageWithFixedCss(): ?string
    {
        $image = $this->getImage();
        return str_replace('img-seva img-responsive', 'img-fluid', $image);
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getFormatedPrice(): ?string
    {
        return number_format($this->getPrice(), 0, ',', '.');
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    public function setLongDescription(?string $longDescription): self
    {
        $this->longDescription = $longDescription;

        return $this;
    }

    public function getLatitud(): ?string
    {
        return $this->latitud;
    }

    public function setLatitud(?string $latitud): self
    {
        $this->latitud = $latitud;

        return $this;
    }

    public function getLongitud(): ?string
    {
        return $this->longitud;
    }

    public function setLongitud(?string $longitud): self
    {
        $this->longitud = $longitud;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getPossible(): ?bool
    {
        return $this->possible;
    }

    public function setPossible(bool $possible): self
    {
        $this->possible = $possible;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(?string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }


}

src/Form/ApartamentoType.php
<?php

namespace App\Form;

use App\Entity\Apartamento;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApartamentoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('url')
            ->add('name')
            ->add('image')
            ->add('price')
            ->add('description')
            ->add('longDescription')
            ->add('latitud')
            ->add('longitud')
            ->add('active')
            ->add('possible')
            ->add('notes')
            //->add('createdAt')
            ->add('hash')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Apartamento::class,
        ]);
    }
}

src/Controller/ApartamentoController.php
<?php

namespace App\Controller;

use App\Entity\Apartamento;
use App\Form\ApartamentoType;
use App\Repository\ApartamentoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/apartamento")
 */
class ApartamentoController extends AbstractController
{
    /**
     * @Route("/", name="apartamento_index", methods={"GET"})
     */
    public function index(ApartamentoRepository $apartamentoRepository): Response
    {
        return $this->render('apartamento/index.html.twig', [
            'apartamentos' => $apartamentoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="apartamento_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $apartamento = new Apartamento();
        $form = $this->createForm(ApartamentoType::class, $apartamento);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $apartamento->setCreatedAt(new \DateTime());
            $entityManager->persist($apartamento);
            $entityManager->flush();

            return $this->redirectToRoute('apartamento_index');
        }

        return $this->render('apartamento/new.html.twig', [
            'apartamento' => $apartamento,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="apartamento_show", methods={"GET"})
     */
    public function show(Apartamento $apartamento): Response
    {
        return $this->render('apartamento/show.html.twig', [
            'apartamento' => $apartamento,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="apartamento_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Apartamento $apartamento): Response
    {
        $form = $this->createForm(ApartamentoType::class, $apartamento);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('apartamento_index');
        }

        return $this->render('apartamento/edit.html.twig', [
            'apartamento' => $apartamento,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{url}", name="apartamento_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Apartamento $apartamento): Response
    {
        if ($this->isCsrfTokenValid('delete'.$apartamento->getUrl(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($apartamento);
            $entityManager->flush();
        }

        return $this->redirectToRoute('apartamento_index');
    }
}

src/Controller/ApartamentosController.php
<?php
/**
 * @copyright Copyright © 2019 Geocom. All rights reserved.
 * @author    Rodrigo Santellan <rsantellan@geocom.com.uy>
 */
namespace App\Controller;

use App\Repository\ApartamentoRepository;
use App\Repository\FocusPointRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Apartamento;

class ApartamentosController extends AbstractController
{

    /**
     * @Route("/", name="index", methods={"GET"})
     * @param ApartamentoRepository $apartamentoRepository
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function index(ApartamentoRepository $apartamentoRepository)
    {
        $quantityActivePossibleInMap = $apartamentoRepository->doCount(true, true, true);
        $quantityActivePossibleNotInMap = $apartamentoRepository->doCount(true, true, false);
        $quantityActiveNotPossibleInMap = $apartamentoRepository->doCount(true, false, true);
        $quantityActiveNotPossibleNotInMap = $apartamentoRepository->doCount(true, false, false);
        $quantityNotActive =  $apartamentoRepository->doCount(false, null, null);
        $data = [
            'active' =>
                [
                    'inmap' => [
                        'posible' => $quantityActivePossibleInMap[1],
                        'notposible' => $quantityActiveNotPossibleInMap[1],
                ],
                    'notmap' => [
                        'posible' => $quantityActivePossibleNotInMap[1],
                        'notposible' => $quantityActiveNotPossibleNotInMap[1],
                    ]
                ],
            'notactive' => $quantityNotActive[1]
        ];
        return $this->render('apartamentos/index.html.twig', ['data' => $data]);
    }

    /**
     * @Route("/actives.html", name="activos", methods={"GET"})
     */
    public function active(ApartamentoRepository $apartamentoRepository)
    {
        $data = $apartamentoRepository->getAllActive();
        return $this->render('apartamentos/activelist.html.twig', ['list' => $data]);
    }

    /**
     * @Route("/inactives.html", name="inactivos", methods={"GET"})
     */
    public function inactive(ApartamentoRepository $apartamentoRepository)
    {
        $data = $apartamentoRepository->getAllActive();
        return $this->render('apartamentos/activelist.html.twig', ['list' => $data]);
    }

    /**
     * @Route("/mapa.html", name="mapa", methods={"GET"})
     * @param ApartamentoRepository $apartamentoRepository
     * @param FocusPointRepository $focusPointRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function map(ApartamentoRepository $apartamentoRepository, FocusPointRepository $focusPointRepository)
    {
        $focusPoints = $focusPointRepository->findAll();
        $focusPointData = [];
        foreach ($focusPoints as $focusPoint) {
            $focusPointData[] = [
                'name' => $focusPoint->getName(),
                'latitud' => $focusPoint->getLatitud(),
                'longitud' => $focusPoint->getLongitud(),
            ];
        }
        $data = $apartamentoRepository->getAllActiveMarkers();
        $sendData = [];
        foreach($data as $apto){
            $aux = new \stdClass();
            $aux->name = $apto['name'];
            $aux->longitud = $apto['longitud'];
            $aux->latitud = $apto['latitud'];
            $aux->url = $this->generateUrl('viewpublication', ['hash' => $apto['hash']]);
            $sendData[] = $aux;
        }
        return $this->render('apartamentos/map.html.twig', ['data' => $sendData, 'focusPoints' => $focusPointData]);
    }
    /**
     * @Route("/apto/{hash}", name="viewpublication", methods={"GET"})
     */
    public function apto(ApartamentoRepository $apartamentoRepository, string $hash)
    {
        $apto = $apartamentoRepository->findOneBy(['hash' => $hash]);
        return $this->render('apartamentos/apto.html.twig', ['apto' => $apto]);
    }
    /**
     * @Route("/nomap.html", name="sinmapa", methods={"GET"})
     */
    public function sinmapa()
    {

    }
}

templates/apartamentos/activelist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listado de activos{% endblock %}

{% block body %}
    {% set counter = 0 %}
    {% set loopCounter = 0 %}
    {% for apartment in list %}
        {% if counter == 0 %}
            <div class="row">
            {% set counter = 1 %}
        {% endif %}
        <div class="col-lg-3">
            <!-- panel-warning -->
            <section class="panel panel-primary">
                <header class="panel-heading"><strong>{{ apartment.name }}</strong></header>
                <div class="panel-body">
                    <div class="image">
                        <a href="{{ apartment.url }}">
                            {{ apartment.imageWithFixedCss | raw }}
                        </a>
                    </div>
                    <div class="price text-center">U$S <strong>{{ apartment.formatedPrice }}</strong></div>
                </div>
            </section>
        </div>
        {% set loopCounter = loopCounter + 1 %}
        {% if loopCounter == 4 %}
            </div>
            {% set counter = 0 %}
            {% set loopCounter = 0 %}
        {% endif %}
    {% endfor %}
    {% if counter == 1 %}
        </div>
    {% endif %}
    <div class="row">

    </div>
{% endblock %}

templates/apartamentos/apto.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{  apto.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1 class="mt-5">{{  apto.name }}</h1>
            <p class="lead">{{  apto.image | raw }}</p>
            <p class="lead">{{  apto.url }}</p>
            <p class="lead">U$S {{  apto.price }}</p>
            <p class="lead">{{  apto.longDescription | raw }}</p>
            <p class="lead">{{  apto.notes }}</p>
            {#{ dump(apto) }#}
        </div>
    </div>
{% endblock %}

templates/apartamentos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}My cool project{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1 class="mt-5">A Bootstrap 4 Starter Template</h1>
            <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            Activos en el mapa
            <span>Posible: <strong>{{ data.active.inmap.posible }}</strong></span>
            <span>No Posible: <strong>{{ data.active.inmap.notposible }}</strong></span>
        </div>
        <div class="col-sm">
            Activos sin mapa
            <span>Posible: <strong>{{ data.active.notmap.posible }}</strong></span>
            <span>No Posible: <strong>{{ data.active.notmap.notposible }}</strong></span>
        </div>
        <div class="col-sm">
            No activos <strong>{{ data.notactive }}</strong>
        </div>
    </div>

{% endblock %}

templates/apartamentos/map-ol.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mapa{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('vendor/openlayer/ol.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('vendor/openlayer/ol.js') }}"></script>
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script>


        var map = new ol.Map({
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            target: 'map',
            view: new ol.View({
                center: ol.proj.fromLonLat([-56.148253, -34.886205]),
                zoom: 12
            })
        });
        var markerList = new Array();
        {% for apartment in data %}
            var description = "{{ apartment.name }}  - {{  apartment.url }}";
            var marker = new ol.Feature({
                geometry: new ol.geom.Point(ol.proj.transform([{{ apartment.longitud }}, {{ apartment.latitud }}], 'EPSG:4326', 'EPSG:3857')),
                description: description,
            });
            /*
            marker.events.register('mousedown', marker,
                function(evt) {
                    alert(this.icon.url); ol.Event.stop(evt);
                }
            );
            */
            markerList.push(marker);
        {% endfor %}
        var markers = new ol.source.Vector({
            features: markerList
        });

        var markerVectorLayer = new ol.layer.Vector({
            source: markers,
        });
        map.addLayer(markerVectorLayer);
        map.on('click', function(evt) {
            var coordinates = evt.coordinate;
            alert(coordinates);
        });
    </script>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <div id="map" class="map"></div>
        </div>
    </div>
{% endblock %}

templates/apartamentos/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mapa{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('vendor/openlayer/ol.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('vendor/openlayer/ol.js') }}"></script>
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script>
        var focusPoints = Array();
        {% for focusPoint in focusPoints %}
        var focusPoint = new Object();
        focusPoint.name = "{{ focusPoint.name }}";
        focusPoint.longitud = {{ focusPoint.longitud }};
        focusPoint.latitud = {{ focusPoint.latitud }};
        focusPoints.push(focusPoint);
        {% endfor %}
        var data = Array();
        {% for apartment in data %}
            var apartment = new Object();
            apartment.title = "{{ apartment.name }}";
            apartment.longitud = {{ apartment.longitud }};
            apartment.latitud = {{ apartment.latitud }};
            apartment.url = '{{ apartment.url }}';
            data.push(apartment);
        {% endfor %}

        var map = new ol.Map({
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            target: 'map',
            view: new ol.View({
                center: ol.proj.fromLonLat([-56.148253, -34.886205]),
                zoom: 12
            })
        });
        var markerList = new Array();

        var style1 = [
            new ol.style.Style({
                image: new ol.style.Icon({
                    scale: .05,
                    src: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Green_Dot.svg",
                    //src: "src/dot.png",
                }),
                zIndex: 5,
            }),
        ];
        for(var apto of data){
            var marker = new ol.Feature({
                geometry: new ol.geom.Point(ol.proj.transform([apto.longitud ,  apto.latitud ], 'EPSG:4326', 'EPSG:3857')),
                description: apto.title,
            });
            marker.setStyle(style1);
            markerList.push(marker);
        }
        for(var focusPoint of focusPoints) {
            var marker = new ol.Feature({
                geometry: new ol.geom.Point(ol.proj.transform([focusPoint.longitud ,  focusPoint.latitud ], 'EPSG:4326', 'EPSG:3857')),
                description: focusPoint.name,
            });
            markerList.push(marker);
            var circle = new ol.geom.Circle(ol.proj.transform([focusPoint.longitud ,  focusPoint.latitud ], 'EPSG:4326', 'EPSG:3857'), 1000);

            var CircleFeature = new ol.Feature(circle);
            var vectorSource = new ol.source.Vector({
                projection: 'EPSG:4326',
            });

            vectorSource.addFeatures([CircleFeature]);


            var layer = new ol.layer.Vector({
                source: vectorSource,
                style: [
                    new ol.style.Style({
                        stroke: new ol.style.Stroke({
                            color: 'blue',
                            width: 3
                        }),
                        fill: new ol.style.Fill({
                            color: 'rgba(0, 0, 255, 0.1)'
                        })
                    })]
            });
            map.addLayer(layer);
        }

        var markers = new ol.source.Vector({
            features: markerList
        });

        var markerVectorLayer = new ol.layer.Vector({
            source: markers,
        });
        map.addLayer(markerVectorLayer);
        map.on('click', function(evt) {
            var delta = 0.01;
            var coordinates =ol.proj.toLonLat(evt.coordinate);
            var minLatitud = Math.abs(coordinates[1]) - delta;
            var maxLatitud = Math.abs(coordinates[1]) + delta;
            var minLongitud = Math.abs(coordinates[0]) - delta;
            var maxLongitud = Math.abs(coordinates[0]) + delta;
            var showModal = new Array();
            var showModalFocus = new Array();
            for(var apto of data){
                if(Math.abs(apto.longitud) >= minLongitud && Math.abs(apto.longitud) <= maxLongitud){
                    if(Math.abs(apto.latitud) >= minLatitud && Math.abs(apto.latitud) <= maxLatitud){
                        showModal.push(apto);
                    }
                }
            }
            for(var focusPoint of focusPoints){
                if(Math.abs(focusPoint.longitud) >= minLongitud && Math.abs(focusPoint.longitud) <= maxLongitud){
                    if(Math.abs(focusPoint.latitud) >= minLatitud && Math.abs(focusPoint.latitud) <= maxLatitud){
                        showModalFocus.push(focusPoint);
                    }
                }
            }
            $('#myModalBody').html('');
            for(var apto of showModal){
                $('#myModalBody').append($("<a>", {
                    title: apto.title,
                    href: apto.url,
                    target: '_blank'
                }).append( apto.title ));
                $('#myModalBody').append($("<br>"));
            }
            $('#myModalBody').append($("<h5>").html('Escuelas'));
            for(var focusPoint of showModalFocus){
                $('#myModalBody').append($("<a>", {
                    title: focusPoint.name,
                    href: 'javascript:void(0)'
                }).append( focusPoint.name ));
                $('#myModalBody').append($("<br>"));
            }
            $('#myModal').modal('show');
        });
    </script>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <div id="map" class="map"></div>
            <div id="myModal" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Propiedades cercanas</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="myModalBody">
                            <p>Modal body text goes here.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}